---
- name: Helpdesk Admin Deployment
  hosts: helpdesk-app
  gather_facts: false
  tasks:
    - name: Reset Commit
      shell: git reset --hard
      args:
        chdir: /root/Prod/helpdesk-admin/
    - name: Clone the Github Repo
      shell: git pull
      args:
        chdir: /root/Prod/helpdesk-admin/
        
    - name: Install Node Modules
      shell: yarn install
      args:
        chdir: /root/Prod/helpdesk-admin/
    - name: Create Build
      shell: yarn build
      args:
        chdir: /root/Prod/helpdesk-admin/
    - name: Restart the Site
      shell: pm2 restart helpdesk-admin-dev
